const demoMovies=[
 {id:1,title:'O Poderoso Chefão',year:1972,score:9.2,group:9.1,member:'Nefasto',date:'2024-10-06',poster:'https://image.tmdb.org/t/p/w200/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',backdrop:'https://image.tmdb.org/t/p/w780/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',overview:'Uma família mafiosa luta para estabelecer sua supremacia nos Estados Unidos enquanto o patriarca envelhece.'},
 {id:2,title:'O Senhor dos Anéis',year:2003,score:9.0,group:8.8,member:'Shaco',date:'2024-09-29',poster:'https://image.tmdb.org/t/p/w200/rrc6GiAKeoE2dVd3vG6BwcZubW.jpg',backdrop:'https://image.tmdb.org/t/p/w780/8x7ej0LnHdKUq4bH7lf9g4V7.jpg',overview:'O último membro de uma sociedade parte em uma jornada para destruir um poderoso anel.'},
 {id:3,title:'A Viagem de Chihiro',year:2001,score:8.6,group:8.7,member:'Pachenko',date:'2024-09-22',poster:'https://image.tmdb.org/t/p/w200/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',backdrop:'https://image.tmdb.org/t/p/w780/Abc.jpg',overview:'Uma menina atravessa um mundo mágico e precisa encontrar coragem para salvar seus pais.'},
 {id:4,title:'Clube da Luta',year:1999,score:8.4,group:8.2,member:'Nefasto',date:'2024-09-15',poster:'https://image.tmdb.org/t/p/w200/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg',overview:'Um homem insone e um vendedor de sabão formam um clube de luta clandestino.'},
 {id:5,title:'Parasita',year:2019,score:8.5,group:8.6,member:'Shaco',date:'2024-09-08',poster:'https://image.tmdb.org/t/p/w200/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',overview:'Uma família desempregada começa a se infiltrar na vida de uma família rica.'},
 {id:6,title:'Interestelar',year:2014,score:8.7,group:8.5,member:'Pachenko',date:'2024-09-01',poster:'https://image.tmdb.org/t/p/w200/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',overview:'Uma equipe de exploradores viaja através de um buraco de minhoca no espaço.'},
 {id:7,title:'Cidade de Deus',year:2002,score:8.6,group:8.9,member:'Nefasto',date:'2024-08-25',poster:'https://image.tmdb.org/t/p/w200/k7eYdWvhYQyRQoU2TB2MoRe4s2B.jpg',overview:'Dois jovens seguem caminhos diferentes numa comunidade marcada pela violência.'},
 {id:8,title:'O Iluminado',year:1980,score:8.4,group:8.0,member:'Shaco',date:'2024-08-18',poster:'https://image.tmdb.org/t/p/w200/9fgh3d4h6q.jpg',overview:'Um escritor aceita um trabalho como zelador de um hotel isolado no inverno.'}
];
const members=[{name:'Pachenko',initial:'P',cls:'user-avatar'},{name:'Nefasto',initial:'N',cls:'avatar-nefasto'},{name:'Shaco',initial:'S',cls:'avatar-shaco'}];
let movies=JSON.parse(localStorage.getItem('domingoMovies')||'null')||demoMovies;let chosenThisWeek=[];let topic='classic';let apiKey=localStorage.getItem('tmdbKey')||window.TMDB_CONFIG?.apiKey||'';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function poster(url){return url||'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=200&q=80'}
function fmtDate(d){if(!d)return'—';return new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.','')}
function member(name){return members.find(m=>m.name===name)||members[0]}
function renderOverview(){
 $('#totalMovies').textContent=String(movies.length).padStart(2,'0');const groupValues=movies.map(m=>Number(m.group)).filter(Number.isFinite);const avg=groupValues.length?groupValues.reduce((a,value)=>a+value,0)/groupValues.length:null;$('#groupAverage').textContent=avg===null?'—':avg.toFixed(1).replace('.',',');
 const next=members.find(m=>!chosenThisWeek.includes(m.name))||members[0];$('#nextChooser').textContent=next.name;$('#heroChooser').textContent=next.name;
 $('#recentList').innerHTML=movies.slice(0,4).map(m=>`<div class="movie-row"><img class="movie-thumb" src="${poster(m.poster)}" onerror="this.src='${poster()}'"><div><div class="movie-title">${m.title}</div><div class="movie-meta">${m.year} · ${m.member}</div></div><span class="score">★ ${m.group||'—'}</span><div class="avatar mini-avatar ${member(m.member).cls}">${member(m.member).initial}</div></div>`).join('');
 $('#membersList').innerHTML=members.map(m=>{let chosen=movies.filter(x=>x.member===m.name);let rated=chosen.filter(x=>Number.isFinite(Number(x.group)));let score=rated.length?(rated.reduce((a,x)=>a+Number(x.group),0)/rated.length).toFixed(1):'—';return `<div class="member-row"><div class="avatar ${m.cls}">${m.initial}</div><div><strong>${m.name}</strong><small>${chosen.length} ${chosen.length===1?'filme escolhido':'filmes escolhidos'}</small></div><div class="member-score"><b>${score}</b><small>média</small></div></div>`}).join('');
}
function renderRoulette(){const eligible=members.map(m=>({...m,disabled:chosenThisWeek.includes(m.name)}));$('#eligibleList').innerHTML=eligible.map(m=>`<div class="eligible-row ${m.disabled?'disabled':''}"><div class="avatar ${m.cls}">${m.initial}</div><div><strong>${m.name}</strong><small>${m.disabled?'já escolheu esta semana':'elegível para sortear'}</small></div><span class="check">${m.disabled?'×':'✓'}</span></div>`).join('')}
function renderHistory(){ $('#historyCount').textContent=`${movies.length} filmes registrados`;$('#historyTable').innerHTML=movies.map((m,i)=>`<tr><td><div class="table-film"><img class="table-poster" src="${poster(m.poster)}" onerror="this.src='${poster()}'"><span>${m.title}<small class="td-muted">${m.year}</small></span></div></td><td><div class="table-film"><div class="avatar mini-avatar ${member(m.member).cls}">${member(m.member).initial}</div>${m.member}</div></td><td class="td-muted">${fmtDate(m.date)}</td><td><span class="score">★ ${m.score||'—'}</span></td><td><span class="score">★ ${m.group||'—'}</span></td><td><button class="delete-row" data-id="${m.id}">×</button></td></tr>`).join('');$$('.delete-row').forEach(b=>b.onclick=()=>{movies=movies.filter(m=>m.id!=b.dataset.id);save();renderAll();toast('Sessão removida do histórico')})}
function renderRanking(){const rows=members.map(m=>{let chosen=movies.filter(x=>m.name===x.member&&Number.isFinite(Number(x.group)));let avg=chosen.length?chosen.reduce((a,x)=>a+Number(x.group),0)/chosen.length:null;return {...m,avg,chosen:chosen.length}}).sort((a,b)=>(b.avg??-1)-(a.avg??-1));$('#rankingList').innerHTML=rows.map((m,i)=>`<div class="rank-row"><span class="rank-pos">0${i+1}</span><div class="rank-person"><div class="avatar ${m.cls}">${m.initial}</div><strong>${m.name}</strong></div><div class="rank-bar-wrap"><div class="rank-bar" style="width:${m.avg===null?0:m.avg*10}%"></div></div><div class="rank-average">${m.avg===null?'—':m.avg.toFixed(1)} <small>${m.chosen} escolhas</small></div></div>`).join('')}
const picks=[...demoMovies].sort((a,b)=>b.score-a.score);function renderDiscover(list=picks){const f=list[0]||picks[0];$('#featuredMovie').style.backgroundImage=`url(${poster(f.backdrop||f.poster)})`;$('#featuredMovie').innerHTML=`<div class="featured-copy"><span class="pill">${topic==='classic'?'CLÁSSICO · TOP 100 IMDb':'SUGESTÃO TMDB'}</span><h2>${f.title}</h2><div class="feature-meta">${f.year} &nbsp; · &nbsp; ★ ${f.score}</div><p>${f.overview}</p><button class="primary-button" data-film="${f.id}" id="featureAdd">＋ adicionar à sessão</button></div>`;$('#suggestionList').innerHTML=list.slice(1,5).map(m=>`<div class="pick-row" data-pick="${m.id}"><img class="pick-poster" src="${poster(m.poster)}"><div><strong>${m.title}</strong><small>${m.year} · ★ ${m.score}</small></div></div>`).join('');$('#featureAdd').onclick=()=>openModal(f)}
function renderAll(){renderOverview();renderRoulette();renderHistory();renderRanking();renderDiscover()}
function save(){localStorage.setItem('domingoMovies',JSON.stringify(movies))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function openModal(f){$('#modalBackdrop').classList.add('open');$('#filmTitle').value=f?.title||'';$('#tmdbScore').value=f?.score||8;$('#filmDate').value=new Date().toISOString().slice(0,10);$('#memberSelect').innerHTML=members.map(m=>`<option>${m.name}</option>`).join('')}
function closeModal(){$('#modalBackdrop').classList.remove('open')}
async function tmdbSearch(q){if(!apiKey)return null;try{const r=await fetch(`https://api.themoviedb.org/3/search/movie?api_key=${apiKey}&language=pt-BR&query=${encodeURIComponent(q)}`);const j=await r.json();return j.results?.map(x=>({id:x.id,title:x.title,year:x.release_date?.slice(0,4)||'',score:(x.vote_average/1).toFixed(1),group:'—',poster:x.poster_path?`https://image.tmdb.org/t/p/w200${x.poster_path}`:'',backdrop:x.backdrop_path?`https://image.tmdb.org/t/p/w780${x.backdrop_path}`:'',overview:x.overview||'Sem descrição disponível.'}))||null}catch(e){return null}}
function navigate(view){$$('.view').forEach(x=>x.classList.remove('active-view'));$(`#view-${view}`).classList.add('active-view');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const label={overview:'VISÃO GERAL',roulette:'ROLETA',discover:'DESCOBRIR FILMES',history:'HISTÓRICO',ranking:'RANKING'}[view];$('#pageLabel').textContent=label;window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));$('#quickAdd').onclick=()=>openModal();$('#historyAdd').onclick=()=>openModal();$('#openAddMember').onclick=()=>toast('Os três membros já estão ativos no clube');$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#sessionForm').onsubmit=e=>{e.preventDefault();const f={id:Date.now(),title:$('#filmTitle').value,year:new Date($('#filmDate').value).getFullYear(),score:$('#tmdbScore').value,group:'—',member:$('#memberSelect').value,date:$('#filmDate').value,poster:''};movies.unshift(f);chosenThisWeek=[...new Set([...chosenThisWeek,f.member])];save();renderAll();closeModal();toast('Sessão registrada com sucesso');};
$('#spinButton').onclick=()=>{const available=members.filter(m=>!chosenThisWeek.includes(m.name));if(!available.length){toast('Todos já escolheram nesta semana');return}const winner=available[Math.floor(Math.random()*available.length)];const wheel=$('#rouletteWheel');wheel.classList.add('spinning');setTimeout(()=>{wheel.classList.remove('spinning');$('#rouletteResult').innerHTML=`<span class="result-icon">✦</span><div><small>RESULTADO DO SORTEIO</small><h3>${winner.name} escolhe o próximo filme.</h3></div>`;toast(`${winner.name} foi sorteado!`)},900)};
$$('.topic').forEach(b=>b.onclick=async()=>{$$('.topic').forEach(x=>x.classList.remove('active'));b.classList.add('active');topic=b.dataset.topic;let result=picks;if(apiKey){const q={classic:'The Godfather',popular:'',scifi:'science fiction',thriller:'thriller'}[topic];result=await tmdbSearch(q)||picks}renderDiscover(result)});$('#morePicks').onclick=()=>renderDiscover([...picks].sort(()=>Math.random()-.5));$('#randomMovie').onclick=()=>{renderDiscover([...picks].sort(()=>Math.random()-.5));toast('Nova sugestão gerada')};$('#searchMovie').onclick=async()=>{const q=$('#movieSearch').value.trim();if(!q)return;const result=await tmdbSearch(q);renderDiscover(result||picks);if(!result)toast('Use uma chave TMDB para buscar títulos reais')};$('#movieSearch').onkeydown=e=>{if(e.key==='Enter')$('#searchMovie').click()};
$('#openSettings').onclick=()=>{$('#settingsBackdrop').classList.add('open');$('#apiKey').value=apiKey};$('#closeSettings').onclick=()=>$('#settingsBackdrop').classList.remove('open');$('#clearKey').onclick=()=>{apiKey='';localStorage.removeItem('tmdbKey');$('#settingsBackdrop').classList.remove('open');toast('Modo demo ativado')};$('#settingsForm').onsubmit=e=>{e.preventDefault();apiKey=$('#apiKey').value.trim();localStorage.setItem('tmdbKey',apiKey);$('#settingsBackdrop').classList.remove('open');toast(apiKey?'Chave TMDB salva':'Modo demo ativado')};
document.addEventListener('click',e=>{const row=e.target.closest('[data-pick]');if(row){const f=picks.find(x=>x.id==row.dataset.pick);if(f)openModal(f)}});renderAll();
