-- Execute este arquivo no Supabase SQL Editor.
-- Nunca coloque a senha postgres ou a service_role key no frontend.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null,
  created_at timestamptz default now()
);

create table if not exists public.movies (
  id text primary key,
  title text not null,
  year int,
  score numeric,
  group_score numeric,
  member text not null,
  date date not null,
  poster text,
  backdrop text,
  overview text,
  ratings jsonb default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_by_username text,
  created_at timestamptz default now()
);

create table if not exists public.movie_ratings (
  id bigint generated by default as identity primary key,
  movie_id text not null references public.movies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating numeric not null check (rating >= 0 and rating <= 10),
  created_at timestamptz default now(),
  unique (movie_id, user_id)
);

alter table public.movies add column if not exists group_score numeric;
alter table public.movies add column if not exists ratings jsonb default '{}'::jsonb;
alter table public.movies add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.movies add column if not exists created_by_username text;

alter table public.profiles enable row level security;
alter table public.movies enable row level security;
alter table public.movie_ratings enable row level security;

drop policy if exists "profiles visible to authenticated" on public.profiles;
create policy "profiles visible to authenticated" on public.profiles for select to authenticated using (true);
drop policy if exists "own profile editable" on public.profiles;
create policy "own profile editable" on public.profiles for update to authenticated using (auth.uid() = id);

drop policy if exists "movies visible to authenticated" on public.movies;
create policy "movies visible to authenticated" on public.movies for select to authenticated using (true);
drop policy if exists "members create movies" on public.movies;
create policy "members create movies" on public.movies for insert to authenticated with check (auth.uid() = created_by);
drop policy if exists "owners update movies" on public.movies;
create policy "owners update movies" on public.movies for update to authenticated using (auth.uid() = created_by) with check (auth.uid() = created_by);
drop policy if exists "owners delete movies" on public.movies;
create policy "owners delete movies" on public.movies for delete to authenticated using (auth.uid() = created_by);

drop policy if exists "ratings visible to authenticated" on public.movie_ratings;
create policy "ratings visible to authenticated" on public.movie_ratings for select to authenticated using (true);
drop policy if exists "members rate movies" on public.movie_ratings;
create policy "members rate movies" on public.movie_ratings for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "owners update ratings" on public.movie_ratings;
create policy "owners update ratings" on public.movie_ratings for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "owners delete ratings" on public.movie_ratings;
create policy "owners delete ratings" on public.movie_ratings for delete to authenticated using (auth.uid() = user_id);
